### ISSUE TITLE
1.16.5 Server crash when generating cluster feature

### ISSUE THREAD

**Issue by WeasleyWalls** [nikita488/ZYCraft#17]
Server crash when exploring, most likely happened when one of our players were exploring but don't have any more information than the crashlog attached below

Minecraft Version: 1.16.5
Modpack: ATM6 1.8.7
Forge Version: 36.2.6

https://pastebin.com/c5qhNRLy

**Comment by nikita488** [comment]
Huh, not sure why this happened, but i'll try add some checks to prevent this.

**Comment by nikita488** [comment]
Fixed in 3.1.3

**Comment by MojangPlsFix** [comment]
Bug is not fixed same crash, but now the server halts not does not crash: https://paste.myftb.de/olobabeyug.sql
Running the newest version with the Modpack ATM 6 1.8.8.

**Comment by nikita488** [comment]
`Caused by: java.lang.NullPointerException: No chunk exists at [-739, -847]` is not a vanilla error, this is from Lithium, but I don't see any Lithium Forge ports installed in ATM 6 modpack. Can you show me your server modlist and plugins?
And provide a full log please.

**Comment by MojangPlsFix** [comment]
[crash-2021-10-29_23.07.11-server.txt](https://github.com/nikita488/ZYCraft/files/7446099/crash-2021-10-29_23.07.11-server.txt)
Here is a crash report with our used Mods. We use a fork of Lithium ported to 1.16 called [Roadrunner](https://github.com/MaxNeedsSnacks/roadrunner), for Performance Reasons. Since this is rather a Roadrunner Issue, I will report it to them.

**Comment by nikita488** [comment]
Yeah, cause I'm not doing anything special with my Quartz Crystal cluster world gen placement, even Vanilla does the same thing in the nether. It's a problem with all Lithium forks I believe, so yeah, report it to them.
